### ISSUE TITLE
Interesting Repo, Is Posible to Deploy React on hosting like godaddy??

### ISSUE THREAD

**Issue by kalvinkrishna** [twe4ked/api-docs#5]
I'm new on React so i found this repostiori using github.io to make it online site for react. but i still not understand how to deploy it into hosting server like godaddy or etc. please help me, thank you

**Comment by twe4ked** [comment]
It can generate static files that can be hosted just about anywhere. I don't have experience hosting things on GoDaddy (but if you haven't got an account I'd steer away from them personally).

Running `npm run build` will create files in the `build/` directory that can then be moved onto any web server set up to expose public files. Generally these will go into a `www` directory or similar.

```
$ npm run build

> api-docs@0.1.0 build /Users/odin/src/api-docs
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  99.31 KB (+514 B)  build/static/js/main.008a7aec.js
  1.07 KB (+293 B)   build/static/css/main.f2f74f49.css

The project was built assuming it is hosted at /api-docs/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
To publish it at https://twe4ked.github.io/api-docs/, run:

  npm run deploy

11.893s total, 10.94s user, 0.93s system, 99% cpu
```

The simplest way is to host this on GitHub pages though as described in the README. I can help you out with the GitHub pages hosting but I won't be much help with another custom hosting solution, sorry.
